### PR TITLE
ARM Enablement

### PR DESCRIPTION
**Pull request by nedrichards**
PR to be used for ARM enablement - do not merge as is - I've disabled all the other arches to reduce load on the build servers.

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
bot, build

**Comment by ramcq** [comment]
Seems to build now. Ship it? @alexlarsson @nedrichards

**Comment by nedrichards** [comment]
Joyful!

**Pull request merged**
