### PR TITLE
Initial test commit for cacerts support

### LINKED ISSUE #2: CA Certificates Is Empty
We're not shipping CA Certs properly for the Java trust root which is [breaking Minecraft](https://github.com/flathub/flathub/pull/160).

> It looks like that the OpenJDK trust store is missing or empty.
I have tried adding -Djavax.net.ssl.trustStore=/app/jre/jvm/openjdk-9/lib/security/cacerts to the Minecraft launch command, but unfortunately, no luck.
I believe Debian has ca-certificates-java package for this, so maybe we could use it.

### PR DESCRIPTION
**Pull request by nedrichards**
An attempt to fix #2 using an approach from https://github.com/digitalstreamio/flatpak-images/tree/master/org.freedesktop.Sdk.Extension.openjdk8

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
OK, this seems to build fine. I'm going to sit through a local build for some real testing - please don't merge until I report back on that.

**Comment by AsciiWolf** [comment]
Any news about this?

**Comment by nedrichards** [comment]
My approach didn't work well and has been obsoleted by java 10 actually
having working cacerts. (Especially since java 9 isn't lts)

**Comment by mbooth101** [comment]
@AsciiWolf Yes, the java 10 extension should work -- I also updated the java 9 extension to 9.0.4, which should also have working cacerts, but it might not be built yet because of https://github.com/flatpak/flatpak-builder/issues/160

@nedrichards If you have permission, would you please retrigger the build of openjdk9? I am unlucky with builders... https://flathub.org/builds/#/builders/2/builds/2055

**Comment by nedrichards** [comment]
willdo, and will close this for now.

**Pull request closed without merging**
